# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'
target 'ThirtyPlayList' do
# Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
     # Pods for ThirtyPlayLIst_Bata
  pod 'RealmSwift'
  # pod 'Realm', git: 'git@github.com:realm/realm-cocoa.git', branch: 'master'
  # pod 'RealmSwift', git: 'git@github.com:realm/realm-cocoa.git', branch: 'master'
  # pod 'Realm', :git => 'https://github.com/realm/realm-cocoa.git', :branch => 'master', :submodules => true

  # pod 'Realm', :git => 'https://github.com/realm/realm-cocoa.git', :branch => 'master'
  # pod 'RealmSwift', :git => 'https://github.com/realm/realm-cocoa.git', :branch => 'master'


end
